name: 'Bump CDK'
description: ''
inputs:
  working-directory:
    description: 'Sets the working directory'
    required: false
  version:
    description: 'Explicit version to set cdk dependencies to'
    required: false
  debug:
    description: 'Sets debug mode'
    required: false
outputs:
  version:
    description: 'The version of CDK that the project has been set to'
runs:
  using: 'node12'
  main: 'dist/index.js'
